### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [Amelia0719/prj-rev-bwfs-dasmoto#1]
_Grade: Satisfactory_

Great job on your project - I loved how you were able to incorporate the `<p>` and `<b>` tag making your HTML very organized! In addition to this, you utilized the `color` property properly which allowed you to incorporate the blue font color. These two aspects of your code helped you meet the design requirements! An area for improvement here is with respect to the overall organization and indentation of your code.

A recommendation here is to review the following article. Try applying the concept and its usage. It will aid you as your projects get more complex. Read it thoroughly and view the examples! Keep up the great work!
[12 Best Practices for HTML](https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/)

**Comment by Amelia0719** [comment]
Thanks for the feedback! I'll review that article.
